languageCode = "en"
pagination.pagerSize = 5
title = "Sheldon Ip"
enableRobotsTXT = true
defaultContentLanguage = 'en'

[languages]
  [languages.en]
    disabled = false
    languageCode = 'en'
    languageDirection = 'ltr'
    languageName = 'English'
    weight = 1
  [languages.zh-hk]
    disabled = true
    languageCode = 'zh-hk'
    languageDirection = 'ltr'
    languageName = '中文 (香港)'
    weight = 2

[sitemap]
  changeFreq = ''
  filename = 'sitemap.xml'
  priority = -1

[Taxonomies]